### PR TITLE
Capitalised the B in Bitcoin

### PR DESCRIPTION
**Pull request by HeroCC**
Simple commit, I capitalised the B in Bitcoin on the cover page.

### CODE REVIEW

**Comment by boshevski** [comment]
Thanks.

**Comment by super3** [comment]
@changetip 1 beer

**Comment by changetip** [comment]
Hi HeroCC, I've delivered a Bitcoin tip worth 1 beer (5.587 mBTC/$3.50) from super3 to your ChangeTip wallet.

**[Learn about ChangeTip](https://www.changetip.com/tip-online/github)

**Comment by rajisangasanga** [comment]
Need tip too :)

**Pull request merged**
